apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-webserver
spec:
 replicas: 3
 selector:
  matchLabels:
   app: flask-web
 template:
  metadata:
    labels:
      app: flask-web
  spec:
    containers:
     - name: flask-web-container
       image: osmankaradeniz31/flask-web-app:v1
       ports:
       - containerPort: 5000