apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-app-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web-app
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
        - name: flask-web-container
          image: osmankaradeniz31/flask-web-app:v1
